apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - image: jenkins/jenkins
        name: jenkinsadmin
        ports:
        - name: jenkinswebport
          containerPort: 8080
        - name: workerport
          containerPort: 50000
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkinshome
      volumes:
        - name: jenkinshome
          hostPath:
            path: /k8s/jenkins_home
---
apiVersion: v1
kind: Service
metadata:
        name: jenkins-service
        labels:
                run: jenkins
        namespace: jenkins
spec:
       type: ClusterIP
       ports:
               - name: adminport
                 targetPort: 8080
                 port: 80
               - name: workerport
                 targetPort: 50000
                 port: 50000
       selector:
               app: jenkins 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: jenkinslistener
 namespace: jenkins
 annotations:
         kubernetes.io/ingress.class: nginx
spec:
 rules:
 - host: jenkins.aast.edu
   http:
         paths:
         - path: /
           pathType: Prefix
           backend:
                   service:
                           name: jenkins-service
                           port:
                                   number: 80
